import { createHash } from "node:crypto";

import { getRedis } from "@/lib/cache/redis";
import { consume, type InsufficientCreditsError } from "@/lib/credits";
import { CREDIT_COSTS, SEARCH_RESULTS_CACHE_HOURS } from "@/lib/credits/costs";
import { ok, type Result } from "@/lib/result";
import { billableFilters, type FeedTab, type FilterValues } from "@/lib/discovery/feed-url";
import type { RequestContext } from "@/lib/context";

// D-072: the default discovery feeds are free; a *filtered* view costs 1
// credit, then re-running or paging the same filters is free for
// SEARCH_RESULTS_CACHE_HOURS -- the same deal as a live search (D-065).
// Charging happens only in an explicit action (Apply / Unlock), never while
// rendering a page, so prefetches and refreshes can't spend credits.

export { billableFilters };

export const FILTERED_FEED_COST = CREDIT_COSTS.filteredFeedSearch;
const UNLOCK_TTL_SECONDS = SEARCH_RESULTS_CACHE_HOURS * 60 * 60;

function unlockKey(userId: string, tab: FeedTab, billable: FilterValues): string {
  const hash = createHash("sha256")
    .update(`${tab}:${JSON.stringify(billable)}`)
    .digest("base64url")
    .slice(0, 22);
  return `feed-unlock:${userId}:${hash}`;
}

export async function isFilteredViewUnlocked(
  ctx: RequestContext,
  tab: FeedTab,
  values: FilterValues,
): Promise<boolean> {
  const billable = billableFilters(values);
  if (!billable) return true;
  return (await getRedis().get(unlockKey(ctx.userId, tab, billable))) !== null;
}

export interface UnlockResult {
  charged: boolean;
}

// idempotencyKey is generated by the client per Apply click (TRD.md §3.4),
// exactly like searchNichesAction: a retried submit never charges twice.
export async function unlockFilteredView(
  ctx: RequestContext,
  tab: FeedTab,
  values: FilterValues,
  idempotencyKey: string,
): Promise<Result<UnlockResult, InsufficientCreditsError>> {
  const billable = billableFilters(values);
  if (!billable) return ok({ charged: false });

  const key = unlockKey(ctx.userId, tab, billable);
  const redis = getRedis();
  if ((await redis.get(key)) !== null) return ok({ charged: false });

  const charged = await consume(ctx, FILTERED_FEED_COST, "Filtered niche search", idempotencyKey);
  if (!charged.ok) return charged;

  await redis.set(key, "1", { ex: UNLOCK_TTL_SECONDS });
  return ok({ charged: true });
}
