import type { Metadata } from 'next'
import { CommentPickerClient } from './CommentPickerClient'
import { RandomCommentPickerContent } from '@/components/tools/RandomCommentPickerContent'

export const metadata: Metadata = {
  title: 'YouTube Random Comment Picker — Pick a Winner Free',
  description:
    'Free YouTube random comment picker for giveaways & contests. Paste your URL and get a fair winner instantly. No signup, no limits. Works on Shorts too.',
  alternates: {
    canonical: 'https://ytniches.com/tools/random-comment-picker',
  },
  openGraph: {
    title: 'YouTube Random Comment Picker — Free Giveaway Tool',
    description:
      'Pick a random winner from your YouTube comments in seconds. Free tool — no login needed. Supports Shorts, keyword filters, and duplicate removal.',
    url: 'https://ytniches.com/tools/random-comment-picker',
    siteName: 'YTNiches',
    images: [{ url: '/og/random-comment-picker.png', width: 1200, height: 630 }],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'YouTube Random Comment Picker — Free, No Login',
    description:
      'Pick a fair giveaway winner from YouTube comments instantly. Works on Shorts and Live. No signup needed.',
    images: ['/og/random-comment-picker.png'],
  },
}

const softwareSchema = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'YouTube Random Comment Picker',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Web',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  description:
    'Free tool to pick a random winner from YouTube comments for giveaways and contests. Supports keyword filters, duplicate removal, Shorts, and YouTube Live. No signup required.',
}

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Pick a Random Winner from YouTube Comments',
  totalTime: 'PT1M',
  step: [
    {
      '@type': 'HowToStep',
      name: 'Copy your YouTube video URL',
      text: "Go to the YouTube video with your giveaway comments. Copy the URL from your browser's address bar, or tap Share → Copy link on mobile.",
    },
    {
      '@type': 'HowToStep',
      name: 'Paste the URL and configure filters',
      text: 'Paste the video URL into the random comment picker above. Set your filters: enable duplicate comment removal, add a keyword filter if your giveaway required a specific phrase, and set a date range if needed.',
    },
    {
      '@type': 'HowToStep',
      name: 'Load comments and run the draw',
      text: 'Click Load Comments to fetch comments via the YouTube API, then click Pick Winner. The tool selects a random comment using a pseudorandom number generator applied to the full comment index.',
    },
    {
      '@type': 'HowToStep',
      name: 'Share the results for transparency',
      text: "Screenshot or screen record the result to show your audience the winner was selected fairly. Announce the winner in a pinned comment or community post with the winner's comment visible.",
    },
  ],
}

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'Is a YouTube random comment picker 100% fair?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes — when you use the duplicate commenter filter. The randomness is generated by a pseudorandom number generator giving every eligible comment an equal probability of selection.',
      },
    },
    {
      '@type': 'Question',
      name: 'Does YouTube have a built-in comment picker or giveaway tool?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: "No — YouTube has no native giveaway tool or random comment picker as of 2026. You need a third-party tool that accesses comments via the YouTube Data API.",
      },
    },
    {
      '@type': 'Question',
      name: 'Can I pick a winner from YouTube Shorts comments?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes — paste any youtube.com/shorts/VIDEO_ID URL into the picker and it works identically to long-form videos. Comments on Shorts are fetched the same way via the YouTube API.',
      },
    },
    {
      '@type': 'Question',
      name: "What's the maximum number of comments a free tool can handle?",
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Most free tools fetch up to 500 comments per draw due to YouTube Data API quota limitations. For videos with 10,000+ comments, a paid tool or TubeBuddy browser extension handles the full set.',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I pick a random winner from a YouTube live stream?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: "This tool supports VOD video comments, not live chat during an active stream. For live chat picking, CommentPicker.com or TubeBuddy offer that functionality. After your stream ends, the replay's comments are accessible.",
      },
    },
    {
      '@type': 'Question',
      name: 'Are YouTube giveaways legal?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes — with conditions. YouTube giveaways are legal in most countries when they follow sweepstakes law. Always include the required disclaimer that the promotion is not sponsored by YouTube. Check local regulations for high-value prizes.',
      },
    },
  ],
}

export default function RandomCommentPickerPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <div className="py-16 px-4">
        <div className="max-w-3xl mx-auto">
          {/* H1 + Introduction */}
          <div className="text-center mb-10">
            <h1 className="font-display font-black text-[36px] sm:text-[44px] leading-tight text-foreground mb-4">
              YouTube Random Comment Picker
            </h1>
            <p className="text-muted text-lg max-w-xl mx-auto mb-4">
              This YouTube random comment picker fetches your video&apos;s comments and selects
              a fair winner by algorithm. Manual picking wastes hours and looks biased to your audience —
              one person thinking the winner was hand-picked destroys trust. Paste your video URL below —
              or scroll down for the complete giveaway guide.
            </p>
            {/* Trust Callout */}
            <div className="inline-flex flex-wrap justify-center gap-x-3 gap-y-1 text-xs text-[#16A34A] font-medium">
              <span>✓ No login required</span>
              <span>✓ Duplicate filter included</span>
              <span>✓ Works on Shorts</span>
              <span>✓ Comments never stored</span>
            </div>
          </div>

          {/* Tool Embed */}
          <CommentPickerClient />
        </div>
      </div>

      {/* SEO Content Below Tool */}
      <RandomCommentPickerContent />
    </>
  )
}
