-- Down:
-- delete from public.discovery_seeds where source = 'manual';

-- Niche-Discovery-Engine.md §6.3 / Appendix A, approved by the owner
-- 2026-09-26. Owner priority is faceless niches: pure faceless formats
-- (documentary, explained, stories, facts, ambient/music, lore/recaps)
-- run first at priority 3; the rest at 5. Editable on /admin/discovery.
insert into public.discovery_seeds (keyword, source, priority) values
  ('ancient history documentary', 'manual', 3),
  ('medieval history explained', 'manual', 3),
  ('mafia history', 'manual', 3),
  ('cold war history', 'manual', 3),
  ('ww2 stories', 'manual', 3),
  ('unsolved mysteries', 'manual', 3),
  ('true crime documentary', 'manual', 3),
  ('serial killer documentary', 'manual', 3),
  ('conspiracy theories explained', 'manual', 3),
  ('dark history', 'manual', 3),
  ('personal finance tips', 'manual', 5),
  ('passive income ideas', 'manual', 5),
  ('stock market explained', 'manual', 3),
  ('real estate investing for beginners', 'manual', 5),
  ('side hustle ideas', 'manual', 5),
  ('luxury lifestyle billionaire', 'manual', 5),
  ('business case study', 'manual', 3),
  ('how brands make money', 'manual', 5),
  ('ai tools tutorial', 'manual', 5),
  ('chatgpt tips', 'manual', 5),
  ('tech explained', 'manual', 3),
  ('future technology', 'manual', 5),
  ('ai news', 'manual', 5),
  ('space documentary', 'manual', 3),
  ('universe explained', 'manual', 3),
  ('black holes explained', 'manual', 3),
  ('ocean mysteries', 'manual', 3),
  ('science facts', 'manual', 3),
  ('stoicism', 'manual', 5),
  ('self improvement tips', 'manual', 5),
  ('dark psychology', 'manual', 5),
  ('motivation speech', 'manual', 5),
  ('productivity tips', 'manual', 5),
  ('philosophy explained', 'manual', 3),
  ('sleep music', 'manual', 3),
  ('rain sounds for sleeping', 'manual', 3),
  ('lofi study music', 'manual', 3),
  ('meditation music', 'manual', 3),
  ('asmr no talking', 'manual', 3),
  ('relaxing ambience', 'manual', 3),
  ('reddit stories', 'manual', 3),
  ('scary stories', 'manual', 3),
  ('bedtime stories for adults', 'manual', 3),
  ('top 10 facts', 'manual', 3),
  ('did you know facts', 'manual', 3),
  ('geography explained', 'manual', 3),
  ('countries compared', 'manual', 3),
  ('animal facts', 'manual', 3),
  ('wildlife documentary', 'manual', 3),
  ('survival stories', 'manual', 3),
  ('bible stories', 'manual', 3),
  ('mythology explained', 'manual', 3),
  ('greek mythology', 'manual', 3),
  ('norse mythology', 'manual', 3),
  ('famous paintings explained', 'manual', 3),
  ('architecture documentary', 'manual', 3),
  ('abandoned places', 'manual', 3),
  ('engineering explained', 'manual', 3),
  ('how it''s made', 'manual', 3),
  ('car history', 'manual', 3),
  ('aviation documentary', 'manual', 3),
  ('military technology', 'manual', 5),
  ('football history', 'manual', 3),
  ('sports documentary', 'manual', 3),
  ('chess explained', 'manual', 3),
  ('video game lore', 'manual', 3),
  ('movie explained', 'manual', 3),
  ('anime recap', 'manual', 3),
  ('book summary', 'manual', 3),
  ('celebrity net worth', 'manual', 5),
  ('royal family history', 'manual', 3),
  ('crypto explained', 'manual', 3),
  ('economics explained', 'manual', 3),
  ('health facts', 'manual', 3),
  ('nutrition myths', 'manual', 5),
  ('cooking without talking', 'manual', 5),
  ('travel documentary', 'manual', 3),
  ('minimalism lifestyle', 'manual', 5),
  ('language learning tips', 'manual', 5),
  ('history of inventions', 'manual', 3)
on conflict (keyword) do nothing;
